services:
  openface_stream:
    build:
      context: openface_stream
    command: src/temp.py --cuda --verbose
    devices:
    - /dev/nvidia0
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    - /dev/nvidia-uvm-tools
    environment:
      CLASSIFIER_MODEL_PATH: /root/data/classifier.pkl
      ISTREAM_PATH: http://ros_stream:8080/stream?topic=/usb_cam/image_raw
      OSTREAM_ADDRESS: 0.0.0.0
      OSTREAM_PORT: 8080
    volumes:
    - /home/ruffsl/Desktop/face_data:/root/data
    - nvidia_driver_375.39:/usr/local/nvidia:ro
    links:
      - ros_stream
  resolvable:
    image: mgood/resolvable
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock
    - /etc/resolv.conf:/tmp/resolv.conf
  ros_stream:
    build:
      context: ros_stream
    command: roslaunch bringup.launch
    devices:
    - /dev/video0:/dev/video0
version: '3'
volumes:
  nvidia_driver_375.39:
    external: true
